#!/bin/bash -eu

. conf/$HOSTNAME.env

CONTAINER_NAME=elastic
CONTAINER_IMAGE=j0057.azurecr.io/elasticsearch
CONTAINER_TAG=7.8.1
CONTAINER_ARGS=(--net sys
                --ip $ELASTIC_IP
                --dns $DNS_SERVER
                --dns-search sys.$DNS_SEARCH
                --name elastic
                --subuidname elastic
                --subgidname elastic
                --env discovery.type=single-node)

cmd_pull() {
    : skopeo copy docker://docker.io/library/elasticsearch:$CONTAINER_TAG docker://$CONTAINER_IMAGE:$CONTAINER_TAG

}

. functions.sh
