#!/bin/bash -eu

. conf/$HOSTNAME.env

CONTAINER_NAME=elastic
CONTAINER_IMAGE=docker.io/library/elasticsearch
CONTAINER_ARGS=(--net sys
                --ip $ELASTIC_IP
                --dns $DNS_SERVER
                --dns-search sys.$DNS_SEARCH
                --name elastic
                --subuidname elastic
                --subgidname elastic
                --env discovery.type=single-node)

cmd_build() {
    : podman pull docker.io/library/elasticsearch:7.8.1
}

. functions.sh
