#!/bin/bash -eu

. conf/$HOSTNAME.env

CONTAINER_NAME=kibana
CONTAINER_IMAGE=j0057.azurecr.io/kibana
CONTAINER_TAG=7.8.1
CONTAINER_ARGS=(--net sys
                --ip $KIBANA_IP
                --dns $DNS_SERVER
                --dns-search sys.$DNS_SEARCH
                --name kibana
                --uidmap 0:111000:2000
                --gidmap 0:111000:2000
                --env "SERVER_NAME=kibana.sys.$DNS_SEARCH"
                --env 'ELASTICSEARCH_HOSTS=["http://elastic:9200/"]')

cmd_pull() {
    : skopeo copy docker://docker.io/library/kibana:$CONTAINER_TAG docker://$CONTAINER_IMAGE:$CONTAINER_TAG
}

. functions.sh
