#!/bin/bash -eu

MINECRAFT_VERSION=1.16.3
MINECRAFT_SERVER_URL=https://launcher.mojang.com/v1/objects/f02f4473dbf152c23d7d484952121db0b36698cb/server.jar
# --> https://www.minecraft.net/en-us/download/server

. conf/$HOSTNAME.env

CONTAINER_NAME=minecraft
CONTAINER_IMAGE=j0057.azurecr.io/minecraft
CONTAINER_ARGS=(--net sys
                --ip $MINECRAFT_IP
                --dns $DNS_SERVER
                --dns-search sys.$DNS_SEARCH
                --volume /srv/minecraft:/srv)

cmd_build() {
    ctr=$(: buildah from j0057.azurecr.io/alpine:3.12)
    trap ": buildah rm $ctr" EXIT

    : buildah run $ctr -- apk add openjdk11-jre-headless
    : buildah copy $ctr $MINECRAFT_SERVER_URL /opt

    : buildah config \
        --author 'Joost Molenaar <jjm@j0057.nl>' \
        --entrypoint '/usr/bin/java -Xmx1024M -Xms1024M -jar /opt/server.jar --nogui' \
        --workingdir '/srv' \
        $ctr

    : buildah commit $ctr $CONTAINER_IMAGE:$TAG-$MINECRAFT_VERSION
    : buildah push $CONTAINER_IMAGE:$TAG-$MINECRAFT_VERSION
}

cmd_init() {
    : install -o $[SUBUID+0] -g $[SUBUID+0] -m 700 -d /srv/minecraft
    : tee /srv/minecraft/eula.txt <<<'eula=true'
}

. functions.sh
