#!/bin/bash -eu

MINECRAFT_VERSION=1.16.2
MINECRAFT_SERVER_URL=https://launcher.mojang.com/v1/objects/c5f6fb23c3876461d46ec380421e42b289789530/server.jar

. conf/$HOSTNAME.env

CONTAINER_NAME=minecraft
CONTAINER_IMAGE=localhost/minecraft
CONTAINER_ARGS=(--net sys
                --ip $MINECRAFT_IP
                --dns $DNS_SERVER
                --dns-search sys.$DNS_SEARCH
                --subuidname minecraft
                --subgidname minecraft
                --volume /srv/minecraft:/srv)

cmd_build() {
    ctr=$(: buildah from 'alpine:3.12')
    trap ": buildah rm $ctr" EXIT

    : buildah run $ctr -- apk add openjdk11-jre-headless
    : buildah copy $ctr $MINECRAFT_SERVER_URL /opt

    : buildah config \
        --author 'Joost Molenaar <jjm@j0057.nl>' \
        --entrypoint '/usr/bin/java -Xmx1024M -Xms1024M -jar /opt/server.jar --nogui' \
        --workingdir '/srv' \
        $ctr

    : buildah commit $ctr minecraft:$(date +%y%m%d%H%M)-$MINECRAFT_VERSION
}

cmd_init() {
    subuid=$(awk '$1=="minecraft"{print $2}' FS=: /etc/subuid)
    : install -o $[subuid+0] -g $[subuid+0] -m 700 -d /srv/minecraft
    : tee /srv/minecraft/eula.txt <<<'eula=true'
}

. functions.sh
