#!/bin/bash -eu

. conf/$HOSTNAME.env

CONTAINER_NAME=named-rec
CONTAINER_IMAGE=j0057.azurecr.io/named-rec
CONTAINER_ARGS=(--net sys
                --ip $NAMED_REC_IP
                --dns $DNS_SERVER
                --dns-search sys.$DNS_SEARCH)

cmd_build() {
    ctr=$(: buildah from j0057.azurecr.io/alpine:3.12)
    trap ": buildah rm $ctr" EXIT
    : buildah run $ctr -- apk add bind
    : buildah copy $ctr named.d/named-rec.conf /etc/bind/named.conf
    : buildah config \
        --author 'Joost Molenaar <jjm@j0057.nl>' \
        --port tcp/53 \
        --port udp/53 \
        --stop-signal TERM \
        --entrypoint '/usr/sbin/named -4 -u named -g 2>&1' \
        $ctr
    : buildah commit $ctr $CONTAINER_IMAGE:$TAG
    : buildah push $CONTAINER_IMAGE:$TAG
}

. functions.sh
