#!/bin/bash -eu

. conf/$HOSTNAME.env

CONTAINER_NAME=openldap
CONTAINER_IMAGE=j0057.azurecr.io/openldap
CONTAINER_ARGS=(--net sys
                --ip $OPENLDAP_IP
                --dns $DNS_SERVER
                --dns-search sys.$DNS_SEARCH
                --subuidname openldap
                --subgidname openldap)

cmd_build() {
    ctr=$(: buildah from alpine:3.13.3)
    trap ": buildah rm $ctr" EXIT

    : buildah run $ctr -- apk add socat openldap openldap-clients openldap-back-mdb
    : buildah run $ctr -- apk add iproute2
    : buildah run $ctr -- install -o ldap -g ldap -m 700 -d /run/openldap
    : buildah run $ctr -- cp /var/lib/openldap/openldap-data/DB_CONFIG.example /var/lib/openldap/openldap-data/DB_CONFIG

    : buildah copy $ctr openldap.d/slapd.conf /etc/openldap
    : buildah copy $ctr openldap.d/ldap.conf /etc/openldap

    : buildah copy $ctr openldap.d/data.ldif /tmp

    : buildah run $ctr -- sh -c 'socat -u unix-recv:/dev/log stdout \
        &  slapd -u ldap -g ldap -f /etc/openldap/slapd.conf \
        && ldapadd -x -D cn=root,dc=gs45,dc=net -w root -f /tmp/data.ldif \
        && rm /tmp/data.ldif \
        && pkill -TERM socat \
        && pkill -TERM slapd'

    # XXX: openldap sadly still logs to syslog (/dev/log), so have to do some ugly trickery to get the logs onto stdout
    # FIXME: should really do this using PODS instead of PUNT-IT-TO-THE-BACKGROUND-AND-HOPE-FOR-THE-BEST
    : buildah config \
        --author 'Joost Molenaar <jjm@j0057.nl>' \
        --entrypoint 'socat -u unix-recv:/dev/log stdout & \
                      exec slapd -u ldap -g ldap -f /etc/openldap/slapd.conf -d 0x100 &> /dev/null' \
        --port tcp/389 \
        --stop-signal TERM \
        $ctr

    : buildah commit $ctr $CONTAINER_IMAGE:$TAG
    : buildah push $CONTAINER_IMAGE:$TAG
}

. $(dirname $0)/functions.sh
