#!/bin/bash -eu

. conf/$HOSTNAME.env

CONTAINER_NAME=stomrin-worker
CONTAINER_IMAGE=j0057.azurecr.io/stomrin-worker
CONTAINER_ARGS=(--net web
                --ip $STOMRIN_WORKER_IP
                --dns $DNS_SERVER
                --dns-search web.$DNS_SEARCH
                --env STOMRIN_WATCH_DIR=/var/lib/stomrin
                --volume /srv/stomrin:/var/lib/stomrin)
CONTAINER_SUBUID_NAME=stomrin

cmd_init() {
    : install -o 115100 -g 115101 -m 700 -d /srv/stomrin
}

cmd_build() {
    pushd ../stomrin/worker &>/dev/null
    : buildah bud -t $CONTAINER_IMAGE:$TAG
    : buildah push $CONTAINER_IMAGE:$TAG
    popd &>/dev/null
}

. functions.sh
