#!/bin/bash -eu

. conf/$HOSTNAME.env

CONTAINER_NAME=transmission
CONTAINER_IMAGE=j0057.azurecr.io/transmission
CONTAINER_ARGS=(--net vpn
                --ip $TRANSMISSION_IP
                --dns $DNS_SERVER
                --dns-search vpn.$DNS_SEARCH
                --cap-add CAP_NET_RAW
                --user transmission:transmission
                "${TRANSMISSION_VOLUMES[@]}"
                --subuidname transmission
                --subgidname transmission)

cmd_build() {
    ctr=$(: buildah from alpine:3.12)
    trap ": buildah rm $ctr" EXIT

    : buildah run $ctr -- apk add transmission-daemon
    : buildah copy $ctr wireguard.d/wait-vpn /bin/wait-vpn
    : buildah config \
        --author 'Joost Molenaar <jjm@j0057.nl>' \
        --cmd "/bin/wait-vpn /usr/bin/transmission-daemon --foreground --auth --username hoi --password hoi --allowed 192.168.178.*,172.23.*.*,172.28.*.* --peerport $TRANSMISSION_PORT" \
        --stop-signal TERM \
        $ctr

    : buildah commit $ctr $CONTAINER_IMAGE:$TAG
    : buildah push $CONTAINER_IMAGE:$TAG
}

. functions.sh
