#!/bin/bash -eu

. conf/$HOSTNAME.env

CONTAINER_NAME=unifi
CONTAINER_IMAGE=docker.io/linuxserver/unifi-controller
CONTAINER_ARGS=(--net mgmt \
                --dns $DNS_SERVER \
                --dns-search mgmt.$DNS_SEARCH \
                --ip $UNIFI_IP \
                --subuidname unifi \
                --subgidname unifi \
                --volume /srv/unifi:/config \
                --env PUID=999 \
                --env PGID=999)

cmd_pull() {
        : podman pull docker://docker.io/linuxserver/unifi-controller:5.12.66-ls56
}

cmd_init() {
        subuid=$(awk '$1=="unifi"{print $2}' FS=: /etc/subuid)
        : install -o $[subuid+999] -g $[subuid+999] -m 700 -d /srv/unifi
}

. $(dirname $0)/functions.sh
