#!/bin/bash -eu

. conf/$HOSTNAME.env

CONTAINER_NAME=unifi
CONTAINER_IMAGE=j0057.azurecr.io/linuxserver/unifi-controller
CONTAINER_TAG=6.0.28-ls83
CONTAINER_ARGS=(--net mgmt \
                --dns $DNS_SERVER \
                --dns-search mgmt.$DNS_SEARCH \
                --ip $UNIFI_IP \
                --volume /srv/unifi:/config \
                --env PUID=999 \
                --env PGID=999)

cmd_pull() {
        : skopeo copy docker://docker.io/linuxserver/unifi-controller:$CONTAINER_TAG docker://$CONTAINER_IMAGE:$CONTAINER_TAG
}

cmd_init() {
        : install -o $[SUBUID+999] -g $[SUBUID+999] -m 700 -d /srv/unifi
}

. $(dirname $0)/functions.sh
