#!/bin/bash -eu
# vim: set list:

. conf/$HOSTNAME.env

if [ -z "${2:-}" ]; then
    CONTAINER_NAME=wireguard
    CONTAINER_ARGS=(--net vpn
                    --ip $WIREGUARD_IP
                    --dns $DNS_SERVER_VPN
                    --subuidname wireguard
                    --subgidname wireguard
                    --sysctl net.ipv4.conf.all.src_valid_mark=1
                    --cap-add NET_ADMIN,NET_RAW)
    SUBUID_NAME=$CONTAINER_NAME
else
    CONTAINER_NAME=$2-wg
    CONTAINER_ARGS=(--net container:$2
                    --userns container:$2
                    --sysctl net.ipv4.conf.all.src_valid_mark=1
                    --cap-add NET_ADMIN,NET_RAW)
    SUBUID_NAME=$2
fi

CONTAINER_IMAGE=j0057.azurecr.io/wireguard

cmd_build() {
    ctr=$(: buildah from alpine:3.12)
    trap ": buildah rm $ctr" EXIT

    : buildah run $ctr -- apk add wireguard-tools iptables ip6tables
    : buildah run $ctr -- apk add patch
    : buildah run $ctr -- patch /usr/bin/wg-quick <<EOF
--- /tmp/wg-quick.orig
+++ /tmp/wg-quick
@@ -239,3 +239,3 @@
 	printf -v nftcmd '%sadd rule %s %s premangle meta l4proto udp meta mark set ct mark \\n' "\$nftcmd" "\$pf" "\$nftable"
-	[[ \$proto == -4 ]] && cmd sysctl -q net.ipv4.conf.all.src_valid_mark=1
+	[[ \$proto == -4 ]] && [[ \$(sysctl -n net.ipv4.conf.all.src_valid_mark) != 1 ]] && cmd sysctl -q net.ipv4.conf.all.src_valid_mark=1
 	if type -p nft >/dev/null; then
EOF

    # TODO: this should sit in a volume, not in the image -- also regenerate keys
    : buildah copy $ctr wireguard.d/vpn.conf /etc/wireguard

    : buildah config \
        --author 'Joost Molenaar <jjm@j0057.nl>' \
        --cmd '/usr/bin/wg-quick up vpn' \
        --stop-signal TERM \
        $ctr
    : buildah commit $ctr $CONTAINER_IMAGE:$(date +%y%m%d%H%M)
}

cmd_init() {
    subuid=$(awk '$1==SN{print $2}' FS=: SN=$SUBUID_NAME /etc/subuid)
    : install -o $subuid -g $subuid -m 500 -d /srv/$CONTAINER_NAME
    : install -o $subuid -g $subuid -m 400 wireguard.d/vpn.conf /srv/$CONTAINER_NAME
}

. functions.sh
