global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ~

rule_files: ~

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: grafana
    static_configs:
      - targets:
          - grafana:3000

  - job_name: node_exporters
    static_configs:
      - targets:
          - muon:9100
