#!/bin/sh

is_up() {
    ip route get 1.1.1.1 | grep '^1.1.1.1 dev vpn' &>/dev/null
}

for i in `seq 40`; do
    is_up && break
    echo "waiting for vpn network device"
    sleep 0.25
done

if ! is_up ; then
    echo "error: can't seem to find vpn network device" >&2
    exit 1
fi

echo "found vpn network device"

exec "$@"
